-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."activity_dim" add column "activity_join_column" text
--  not null;
