-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO tag_relations (value) VALUES
--     ('dataset'),
--     ('narrative'),
--     ('metric')
-- ON CONFLICT (value) DO NOTHING;
