name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - name: Yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn install --frozen-lockfile --pure-lockfile
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: shell
          filters: |
            changed:
              - added|modified: '**'
      - name: Run ESLint
        run: |
          yarn lint --output-file eslint_report.json --format json ${{ steps.filter.outputs.changed_files }}
        continue-on-error: true
      - name: Annotate Code
        uses: ataylorme/eslint-annotate-action@v3
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          report-json: 'eslint_report.json'

  typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - name: Yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn install --frozen-lockfile --pure-lockfile
      - name: Type check
        run: |
          yarn type-check
