name: 'Review'
on:
  pull_request:
    branches:
      - main
      - production
    types:
      - opened
      - edited

jobs:
  task-check:
    # Skip for dependabot PRs
    if: ${{ !contains( github.head_ref, 'dependabot' ) }}
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/task-completed-checker-action@v0.1.1
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
