-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."company_table" add column "customer_dim_table_id" uuid
--  null;
