-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."narrative" add column "snapshot_updated_at" timestamp with time zone
--  null;
