export const FRAMES = {
  xs: {
    all: 'p-0.5',
    x: 'px-0.5',
    y: 'py-0.5',
    top: 'pt-0.5',
    bottom: 'pb-0.5',
    left: 'pl-0.5',
    right: 'pr-0.5',
  },
  sm: {
    all: 'p-1',
    x: 'px-1',
    y: 'py-1',
    top: 'pt-1',
    bottom: 'pb-1',
    left: 'pl-1',
    right: 'pr-1',
  },
  md: {
    all: 'p-2',
    x: 'px-2',
    y: 'py-2',
    top: 'pt-2',
    bottom: 'pb-2',
    left: 'pl-2',
    right: 'pr-2',
  },
  lg: {
    all: 'p-3',
    x: 'px-3',
    y: 'py-3',
    top: 'pt-3',
    bottom: 'pb-3',
    left: 'pl-3',
    right: 'pr-3',
  },
  xl: {
    all: 'p-4',
    x: 'px-4',
    y: 'py-4',
    top: 'pt-4',
    bottom: 'pb-4',
    left: 'pl-4',
    right: 'pr-4',
  },
  '2xl': {
    all: 'p-5',
    x: 'px-5',
    y: 'py-5',
    top: 'pt-5',
    bottom: 'pb-5',
    left: 'pl-5',
    right: 'pr-5',
  },
  '3xl': {
    all: 'p-6',
    x: 'px-6',
    y: 'py-6',
    top: 'pt-6',
    bottom: 'pb-6',
    left: 'pl-6',
    right: 'pr-6',
  },
}
