-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE INDEX dim_team_permission_idx ON team_permission (related_id) WHERE related_to = 'dim';
