name: Prepare

on:
  pull_request:

jobs:
  test_release:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: restore lerna
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: install
        run: yarn --silent install --frozen-lockfile --pure-lockfile --summary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: build
        run: yarn build
        env:
          NODE_ENV: production

      - name: dry run
        run: yarn lerna:semantic-release
        env:
          NODE_ENV: production
