name: Release

on:
  push:
    branches:
      - master
      - next

jobs:
  release:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needs full history in order to generate changelogs etc

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: restore lerna
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: install
        run: yarn --silent install --frozen-lockfile --pure-lockfile --summary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: release
        run: |
          yarn --silent lerna:semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GH_TOKEN }}

      - run: git diff
