-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."llm_training" add column "in_production" boolean
--  null default 'True';
