-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."company" add column "allow_narrator_employee_access" boolean
--  not null default 'true';
