/* eslint-disable max-lines-per-function */
import { compileTabs } from './tabCompilers'

describe('', () => {
  it('should return tokens that produce "Plotting: <gt>Conversion Rate to Completed Order Between</gt> by <gt>Month</gt> using <b>line</b> plot"', () => {
    const tabs = [
      {
        kind: 'parent',
        slug: 'parent_duplicate',
        label: 'PARENT',
        parentFilters: [{ logicalOperator: 'AND', operands: [] }],
        order: [{ columnId: 'ats_5548547d', asc: false }],
        hideShow: { mode: 'show', columnIds: ['aactivity_id_34f06259', 'ats_5548547d', 'acustomer_00a530c1'] },
        columns: [],
        aggregateDims: [],
        plots: [],
      },
      {
        kind: 'group',
        slug: 'month0798ca01',
        label: 'by Month',
        parentFilters: [{ logicalOperator: 'AND', operands: [] }],
        order: [{ columnId: 'amonth_fb0721d9', asc: false }],
        hideShow: null,
        columns: [
          {
            id: 'amonth_fb0721d9',
            label: 'Month',
            type: 'timestamp',
            filters: [{ logicalOperator: 'AND', operands: [], isNot: false }],
            output: true,
            displayFormat: null,
            pinned: null,
            order: 0,
            details: { kind: 'group', columnId: 'amonth_d1989ec4', pivoted: false, useAsColumn: false },
          },
          {
            id: 'atotal_opened_email_rows_a25753c1',
            label: 'Total Opened Email Rows',
            type: 'number',
            filters: [{ logicalOperator: 'AND', operands: [], isNot: false }],
            output: true,
            displayFormat: 'number',
            pinned: null,
            order: 0,
            details: {
              kind: 'metric',
              aggFunction: 'count_all',
              pivotedOn: null,
              columnId: null,
              percentile: null,
              conditionedOnColumns: null,
            },
          },
          {
            id: 'atotal_completed_order_between_6325f4ed',
            label: 'Total Completed Order Between',
            type: 'number',
            filters: [{ logicalOperator: 'AND', operands: [], isNot: false }],
            output: true,
            displayFormat: 'number',
            pinned: null,
            order: 0,
            details: {
              kind: 'metric',
              aggFunction: 'sum',
              pivotedOn: null,
              columnId: 'adid_completed_order_c02f2449',
              percentile: null,
              conditionedOnColumns: null,
            },
          },
          {
            id: 'aconversion_rate_to_completed_o_ab730c8b',
            label: 'Conversion Rate to Completed Order Between',
            type: 'number',
            filters: [{ logicalOperator: 'AND', operands: [], isNot: false }],
            output: true,
            displayFormat: 'percent',
            pinned: null,
            order: 0,
            details: {
              kind: 'metric',
              aggFunction: 'average',
              pivotedOn: null,
              columnId: 'adid_completed_order_c02f2449',
              percentile: null,
              conditionedOnColumns: null,
            },
          },
          {
            id: 'aaverage_days_to_completed_orde_5e662212',
            label: 'Average Days To Completed Order',
            type: 'number',
            filters: [{ logicalOperator: 'AND', operands: [], isNot: false }],
            output: true,
            displayFormat: 'number',
            pinned: null,
            order: 0,
            details: {
              kind: 'metric',
              aggFunction: 'average',
              pivotedOn: null,
              columnId: 'aday_completed_order_2feb4dd3',
              percentile: null,
              conditionedOnColumns: null,
            },
          },
        ],
        aggregateDims: [],
        plots: [
          {
            name: 'Conversion Rate to Completed Order Between by Month',
            slug: 'conversion_rate_to_completed_order_between_by_month',
            config: {
              columns: {
                y2Available: false,
                ys: ['aconversion_rate_to_completed_o_ab730c8b'],
                xs: ['amonth_fb0721d9'],
                colorBys: [],
                y2: null,
              },
              axes: {
                autogenTitle: 'Conversion Rate to Completed Order Between by Month',
                title: 'Conversion Rate to Completed Order Between by Month',
                yAxis: 'Conversion Rate to Completed Order Between',
                xAxis: 'Month',
                yLog: false,
                y2Axis: '',
                plotKind: 'line',
                smooth: true,
                yStart: null,
                yEnd: null,
                addConversion: false,
                showLabels: false,
                addSliders: true,
                sliderStart: 0,
                sliderEnd: 100,
                isPercent: false,
                hideLegend: false,
                sharedHover: false,
                highlightOnLegend: true,
                addHoverHighlighting: false,
                addBrush: false,
                replace01WithDid: false,
                addRegressionLine: null,
                overideThemeColors: false,
                plotColors: null,
                y2Color: '#5AD8A6',
                y2LineDash: true,
                hiddenValues: [],
                limitRows: null,
                clusterXValues: false,
                addAnimation: false,
                animationDuration: 1000,
              },
              annotations: [],
              question: 'what is my email to order rate over time?',
            },
          },
        ],
      },
      {
        kind: 'group',
        slug: 'campaign_typec983506a',
        label: 'by Campaign Type',
        parentFilters: [{ logicalOperator: 'AND', operands: [] }],
        order: [{ columnId: 'atotal_opened_email_rows_ab34b2d6', asc: false }],
        hideShow: null,
        columns: [
          {
            id: 'acampaign_type_f38d2167',
            label: 'Campaign Type',
            type: 'string',
            filters: [{ logicalOperator: 'AND', operands: [], isNot: false }],
            output: true,
            displayFormat: null,
            pinned: null,
            order: 0,
            details: {
              kind: 'group',
              columnId: 'afeature_campaign_type_775a7670',
              pivoted: false,
              useAsColumn: false,
            },
          },
          {
            id: 'atotal_opened_email_rows_ab34b2d6',
            label: 'Total Opened Email Rows',
            type: 'number',
            filters: [{ logicalOperator: 'AND', operands: [], isNot: false }],
            output: true,
            displayFormat: 'number',
            pinned: null,
            order: 0,
            details: {
              kind: 'metric',
              aggFunction: 'count_all',
              pivotedOn: null,
              columnId: null,
              percentile: null,
              conditionedOnColumns: null,
            },
          },
          {
            id: 'atotal_completed_order_between_3c79e80c',
            label: 'Total Completed Order Between',
            type: 'number',
            filters: [{ logicalOperator: 'AND', operands: [], isNot: false }],
            output: true,
            displayFormat: 'number',
            pinned: null,
            order: 0,
            details: {
              kind: 'metric',
              aggFunction: 'sum',
              pivotedOn: null,
              columnId: 'adid_completed_order_c02f2449',
              percentile: null,
              conditionedOnColumns: null,
            },
          },
          {
            id: 'aconversion_rate_to_completed_o_18ae94d3',
            label: 'Conversion Rate to Completed Order Between',
            type: 'number',
            filters: [{ logicalOperator: 'AND', operands: [], isNot: false }],
            output: true,
            displayFormat: 'percent',
            pinned: null,
            order: 0,
            details: {
              kind: 'metric',
              aggFunction: 'average',
              pivotedOn: null,
              columnId: 'adid_completed_order_c02f2449',
              percentile: null,
              conditionedOnColumns: null,
            },
          },
          {
            id: 'aaverage_days_to_completed_orde_8492cb1a',
            label: 'Average Days To Completed Order',
            type: 'number',
            filters: [{ logicalOperator: 'AND', operands: [], isNot: false }],
            output: true,
            displayFormat: 'number',
            pinned: null,
            order: 0,
            details: {
              kind: 'metric',
              aggFunction: 'average',
              pivotedOn: null,
              columnId: 'aday_completed_order_2feb4dd3',
              percentile: null,
              conditionedOnColumns: null,
            },
          },
        ],
        aggregateDims: [],
        plots: [],
      },
    ]

    const result = compileTabs(tabs, 'month0798ca01', 'conversion_rate_to_completed_order_between_by_month')

    const expected = [
      { format: 'regular', value: 'Plotting:' },
      { format: 'regular', value: ' ' },
      { format: 'greenTag', value: 'Conversion Rate to Completed Order Between' },
      { format: 'regular', value: ' ' },
      { format: 'regular', value: 'by' },
      { format: 'regular', value: ' ' },
      { format: 'greenTag', value: 'Month' },
      { format: 'regular', value: ' ' },
      { format: 'regular', value: 'using' },
      { format: 'regular', value: ' ' },
      { format: 'bold', value: 'line' },
      { format: 'regular', value: ' ' },
      { format: 'regular', value: 'plot' },
    ]
    expect(result).toEqual(expected)
  })
})
