-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE INDEX dataset_versions_idx ON versions (related_id) WHERE related_to = 'dataset';
