{{- if .Values.serviceAccountWorker.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mavis-worker-deployment
  labels:
   {{- include "mavis.labels" . | nindent 4 }}
 {{- with .Values.serviceAccountWorker.annotations }}
  annotations:
   {{- toYaml . | nindent 4 }}
 {{- end }}
{{- end }}
