{{- if .Values.serviceAccountHeartbeat.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mavis-heartbeat-deployment
  labels:
   {{- include "mavis.labels" . | nindent 4 }}
 {{- with .Values.serviceAccountHeartbeat.annotations }}
  annotations:
   {{- toYaml . | nindent 4 }}
 {{- end }}
{{- end }}
