-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."training_request" add column "email_sent_at" timestamptz
--  null;
