{{- if .Values.spec.apps.hasura.createProject -}}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.spec.apps.hasura.project | default "hasura" }}
  namespace: {{ .Values.argoProjectNamespace | default "argocd" }}
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destinations:
    - namespace: {{ .Values.spec.apps.hasura.namespace | default "hasura" }}
      server: {{ .Values.destinationServer | default .Values.spec.destination.server }}
  sourceRepos:
    - {{ .Values.spec.apps.hasura.repoURL }}
  {{- with .Values.sourceNamespaces }}
  sourceNamespaces:
    {{- toYaml .| nindent 4 }}
  {{- end }}
---
  {{- end }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.spec.apps.hasura.name | default "hasura" }}
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: {{ .Values.argoProject | default "default" }}
  destination:
    namespace: {{ .Values.spec.apps.hasura.namespace | default "backend" }}
    server: {{ .Values.destinationServer | default .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.apps.hasura.repoURL }}
    targetRevision: {{ .Values.spec.apps.hasura.targetRevision }}
    path: {{ .Values.spec.apps.hasura.path }}
    helm:
    {{- toYaml .Values.spec.apps.hasura.helm | nindent 6 }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=false