INSERT INTO access_role (value, description) VALUES
('view_dataset', 'User can view a dataset and index page'),
('view_chat', 'User can view the chat in home page'),
('view_report', 'User can view a report and index page'),
('view_activities', 'User can view activities that we currently have'),
('view_processing', 'User can view processing page'),
('view_customer_journey', 'User can view customer journey page'),
('view_billing', 'User can view billing page'),
('create_chat', 'User can create and view a new chat'),
('create_report', 'User can create and view a new report'),
('create_dataset', 'User can create and view a new dataset'),
('create_dataset_materialize_view', 'User can create a new materialize view or view'),
('create_dataset_integeration', 'User can create a new integration (other than warehouse ones)'),
('create_dataset_training', 'User can add a training to a dataset'),
('download_data', 'User can download the data from dataset'),
('can_use_sql', 'User can write SQL and run it'),
('manage_transformations', 'User can create, update and delete transformations'),
('manage_tickets', 'User can view and manage requests'),
('manage_tags', 'User can create tags'),
('manage_api', 'User can manage api'),
('manage_processing', 'User can manage processing'),
('manage_processing_config', 'User can update the Processing configuration in setting'),
('manage_custom_function', 'User can manage and view custom functions'),
('manage_connection', 'User can view and update warehouse connection'),
('manage_billing', 'User can view and update the billing page'),
('manage_users', 'User can view and edit users');
