-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."company" add column "cloud_region" text
--  not null default 'us';
