apiVersion: v2
name: reloader
description: A Helm chart for installing Reloader
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: reloader
    version: 1.0.29
    repository: https://stakater.github.io/stakater-charts
