-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE INDEX narrative_run_versions_idx ON versions (related_id, created_at DESC) WHERE related_to = 'narrative_run' ;
